# Generated by Django 3.1.2 on 2021-05-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210502_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_comprador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_repartidor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
